### ISSUE TITLE
Error in buffermagrd - buffers/qos configurations

### ISSUE THREAD

**Issue by ahmedcs** [Azure/SONiC#195]
Hi all,

The platform is AS7712-32X, 4 end-hosts connected to it through DAC cables.

Please find the below warning generated in the syslog when we try to run the buffers/ports configuration JSON files given. It complains about the cable length not being set. Even though it shows as warning i did print the config-db (using redis-dump) but the configurations are not inserted. Let us know how to fix this.

Config Files: https://github.com/Azure/sonic-swss/pull/441/files

Commands: 

1. Copy the configuration JSON file to the docker, swss
$ docker cp th.32ports.buffers.json swss:/root/th.32ports.buffers.json
$ docker cp th.32ports.qos.json swss:/root/th.32ports.qos.json

2. Configure the speed via the configuration JSON file
$ docker exec -i swss swssconfig /root/th.32ports.buffers.json
$ docker exec -i swss swssconfig /root/th.32ports.qos.json

Errors:

May 21 04:07:21.616392 sonic NOTICE swssconfig: :- main: Loading config from JSON file:/root/th.32ports.buffers.json...
May 21 04:07:21.616392 sonic NOTICE swssconfig: :- main: Loading config from JSON file:/root/th.32ports.qos.json...
May 21 04:07:21.678899 sonic WARNING buffermgrd: :- doSpeedUpdateTask: Unable to create/update PG profile for port Ethernet0. Cable length is not set
May 21 04:07:21.678899 sonic WARNING buffermgrd: :- doSpeedUpdateTask: Unable to create/update PG profile for port Ethernet16. Cable length is not set
May 21 04:07:21.678899 sonic WARNING buffermgrd: :- doSpeedUpdateTask: Unable to create/update PG profile for port Ethernet24. Cable length is not set
May 21 04:07:21.678930 sonic WARNING buffermgrd: :- doSpeedUpdateTask: Unable to create/update PG profile for port Ethernet8. Cable length is not set

There also this error which may/may not be relevant

May 21 04:07:19.649794 sonic ERR snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py", line 45, in start#012    self.update_data()#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/ietf/rfc4363.py", line 72, in update_data#012    vlanmac = fdb_vlanmac(self.db_conn, fdb)#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/ietf/rfc4363.py", line 14, in fdb_vlanmac#012    vlan_id = port_util.get_vlan_id_from_bvid(db_conn, fdb["bvid"])#012  File "/usr/local/lib/python3.6/dist-packages/swsssdk/port_util.py", line 79, in get_vlan_id_from_bvid#012    vlan_id = vlan_entry[b"SAI_VLAN_ATTR_VLAN_ID"]#012KeyError: b'SAI_VLAN_ATTR_VLAN_ID'

Any help on this would be appreciated.

Best,

Ahmed

**Comment by mkbalani** [comment]
Its been a long time, so I guess you already found a solution. But just in case this still is an issue, you can look here
https://github.com/Azure/SONiC/wiki/Buffers-Configuration-Update-design

**Comment by ahmedcs** [comment]
We resolved it, thanks for your reply though
