### ISSUE TITLE
ERROR: MIBUpdater.start() caught an unexpected exception during update_data()

### ISSUE THREAD

**Issue by maq123** [Azure/SONiC#225]
```
Jul 31 10:21:15.002731 sonic INFO snmp/supervisord: snmp-subagent ERROR:ax_interface:MIBUpdater.start() caught an unexpected exception during update_data()
Jul 31 10:21:15.002773 sonic INFO snmp/supervisord: snmp-subagent Traceback (most recent call last):
Jul 31 10:21:15.002935 sonic INFO snmp/supervisord: snmp-subagent   File "/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py", line 40, in start
Jul 31 10:21:15.003000 sonic INFO snmp/supervisord: snmp-subagent     self.reinit_data()
Jul 31 10:21:15.003148 sonic INFO snmp/supervisord: snmp-subagent   File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/vendor/cisco/ciscoSwitchQosMIB.py", line 79, in reinit_data
Jul 31 10:21:15.003148 sonic INFO snmp/supervisord: snmp-subagent     mibs.init_sync_d_queue_tables(self.db_conn)
Jul 31 10:21:15.003378 sonic INFO snmp/supervisord: snmp-subagent   File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/__init__.py", line 184, in init_sync_d_queue_tables
Jul 31 10:21:15.003470 sonic INFO snmp/supervisord: snmp-subagent     queue_name_map = db_conn.get_all(COUNTERS_DB, COUNTERS_QUEUE_NAME_MAP, blocking=True)
Jul 31 10:21:15.003576 sonic INFO snmp/supervisord: snmp-subagent   File "/usr/local/lib/python3.6/dist-packages/swsssdk/interface.py", line 38, in wrapped
Jul 31 10:21:15.003664 sonic INFO snmp/supervisord: snmp-subagent     ret_data = f(inst, db_name, *args, **kwargs)
Jul 31 10:21:15.003766 sonic INFO snmp/supervisord: snmp-subagent   File "/usr/local/lib/python3.6/dist-packages/swsssdk/interface.py", line 310, in get_all
Jul 31 10:21:15.003806 sonic INFO snmp/supervisord: snmp-subagent     raise UnavailableDataError(message, _hash)
Jul 31 10:21:15.003806 sonic INFO snmp/supervisord: snmp-subagent swsssdk.exceptions.UnavailableDataError: Key 'b'COUNTERS_QUEUE_NAME_MAP'' unavailable in database 'COUNTERS_DB'
Jul 31 10:22:15.067613 sonic ERR snmp/snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py", line 40, in start#012    self.reinit_data()#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/vendor/cisco/ciscoPfcExtMIB.py", line 40, in reinit_data#012    self.update_data()#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/vendor/cisco/ciscoPfcExtMIB.py", line 49, in update_data#012    for sai_id in self.if_id_map}#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/vendor/cisco/ciscoPfcExtMIB.py", line 49, in <dictcomp>#012    for sai_id in self.if_id_map}#012  File "/usr/local/lib/python3.6/dist-packages/swsssdk/interface.py", line 38, in wrapped#012    ret_data = f(inst, db_name, *args, **kwargs)#012  File "/usr/local/lib/python3.6/dist-packages/swsssdk/interface.py", line 310, in get_all#012    raise UnavailableDataError(message, _hash)#012swsssdk.exceptions.UnavailableDataError: Key 'b'COUNTERS:oid:0x1000000000021'' unavailable in database 'COUNTERS_DB'
Jul 31 10:22:15.068170 sonic INFO snmp/supervisord: snmp-subagent ERROR:ax_interface:MIBUpdater.start() caught an unexpected exception during update_data()
Jul 31 10:22:15.068268 sonic INFO snmp/supervisord: snmp-subagent Traceback (most recent call last):
Jul 31 10:22:15.068360 sonic INFO snmp/supervisord: snmp-subagent   File "/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py", line 40, in start
Jul 31 10:22:15.068452 sonic INFO snmp/supervisord: snmp-subagent     self.reinit_data()
Jul 31 10:22:15.068540 sonic INFO snmp/supervisord: snmp-subagent   File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/vendor/cisco/ciscoPfcExtMIB.py", line 40, in reinit_data
Jul 31 10:22:15.068689 sonic INFO snmp/supervisord: snmp-subagent     self.update_data()
Jul 31 10:22:15.068689 sonic INFO snmp/supervisord: snmp-subagent   File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/vendor/cisco/ciscoPfcExtMIB.py", line 49, in update_data
Jul 31 10:22:15.068689 sonic INFO snmp/supervisord: snmp-subagent     for sai_id in self.if_id_map}
Jul 31 10:22:15.068742 sonic INFO snmp/supervisord: snmp-subagent   File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/vendor/cisco/ciscoPfcExtMIB.py", line 49, in <dictcomp>
Jul 31 10:22:15.068742 sonic INFO snmp/supervisord: snmp-subagent     for sai_id in self.if_id_map}
Jul 31 10:22:15.068774 sonic INFO snmp/supervisord: snmp-subagent   File "/usr/local/lib/python3.6/dist-packages/swsssdk/interface.py", line 38, in wrapped
Jul 31 10:22:15.068934 sonic INFO snmp/supervisord: snmp-subagent     ret_data = f(inst, db_name, *args, **kwargs)
Jul 31 10:22:15.068934 sonic INFO snmp/supervisord: snmp-subagent   File "/usr/local/lib/python3.6/dist-packages/swsssdk/interface.py", line 310, in get_all
Jul 31 10:22:15.068934 sonic INFO snmp/supervisord: snmp-subagent     raise UnavailableDataError(message, _hash)
Jul 31 10:22:15.068934 sonic INFO snmp/supervisord: snmp-subagent swsssdk.exceptions.UnavailableDataError: Key 'b'COUNTERS:oid:0x1000000000021'' unavailable in database 'COUNTERS_DB'
```

```
admin@sonic:~$ show platform  summary
Platform: x86_64-arista_7050_qx32s
HwSKU: Arista-7050-QX-32S
ASIC: broadcom
```

I use the image I built myself from a master branch.
```
admin@sonic:~$ show version
SONiC Software Version: SONiC.master.0-dirty-20180704.234041
Distribution: Debian 8.11
Kernel: 3.16.0-5-amd64
Build commit: 73a2e64
Build date: Wed Jul  4 23:46:39 UTC 2018
Built by: sonic@crankcees
```

**Comment by stcheng** [comment]
@qiluo-msft have you seen this before?

**Comment by qiluo-msft** [comment]
As log said
```
Key 'b'COUNTERS_QUEUE_NAME_MAP'' unavailable in database 'COUNTERS_DB'
```
It's a non snmp issue.

**Comment by pavel-shirshov** [comment]
Actually I'd check in snmp that the key exists before retrieve it .

**Comment by sripalnati** [comment]
Actually, I see similar error in 2 different boxes, where COUNTERS_DB doesn't have the queue_stat_name [= queue_table(sai_id)] in one case and another scenario it doesn't have COUNTERS_PORT_NAME_MAP key. Both of them are giving traceback error in the syslog.

Aug 23 21:33:16.244622 switch ERR snmp/snmp-subagent [sonic_ax_impl] ERROR: No queue stat counters found in the Counter DB. SyncD database is incoherent.
Aug 23 21:33:16.244856 switch ERR snmp/snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py", line 40, in start#012    self.reinit_data()#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/vendor/cisco/ciscoSwitchQosMIB.py", line 79, in reinit_data#012    mibs.init_sync_d_queue_tables(self.db_conn)#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/__init__.py", line 220, in init_sync_d_queue_tables#012    raise RuntimeError('The queue_stat_map is not defined')#012RuntimeError: The queue_stat_map is not defined

Scenario-2:
=========
Aug 23 21:38:47.575152 kings9 ERR snmp/snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py", line 40, in start#012    self.reinit_data()#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/ieee802_1ab.py", line 53, in reinit_data#012    self.oid_name_map = mibs.init_sync_d_interface_tables(self.db_conn)#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/__init__.py", line 88, in init_sync_d_interface_tables#012    if_name_map, if_id_map = port_util.get_interface_oid_map(db_conn)#012  File "/usr/local/lib/python3.6/dist-packages/swsssdk/port_util.py", line 40, in get_interface_oid_map#012    if_name_map = db.get_all('COUNTERS_DB', 'COUNTERS_PORT_NAME_MAP', blocking=True)#012  File "/usr/local/lib/python3.6/dist-packages/swsssdk/interface.py", line 38, in wrapped#012    ret_data = f(inst, db_name, *args, **kwargs)#012  File "/usr/local/lib/python3.6/dist-packages/swsssdk/interface.py", line 310, in get_all#012    raise UnavailableDataError(message, _hash)#012swsssdk.exceptions.UnavailableDataError: Key 'COUNTERS_PORT_NAME_MAP' unavailable in database 'COUNTERS_DB'

**Comment by Linda-Guo** [comment]
I meet the similiar issue like Scenario-2: and now search way to solve the issue.

**Comment by sripalnati** [comment]
Hi Linda, 
How are you approaching this to solve?

**Comment by k86td** [comment]
Hello, I'm having the same messages in the logs, does someone has a fix for this?
