### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'Vlan500' while adding / fetching VLAN interface in ACL table

### ISSUE THREAD

**Issue by chaitanc** [Azure/SONiC#273]
I tried to add VLAN to ACL as part of this, I used below config

```
"ACL_TABLE": {
        "1": {
            "stage": "INGRESS", 
            "type": "L3", 
            "ports": "Vlan500", 
            "policy_desc": "Counter"
        }, 
        "3": {
            "stage": "INGRESS", 
            "type": "L3V6", 
            "ports": "Ethernet36", 
            "policy_desc": "L3V6 ACL"
        }
 },
"ACL_RULE": {
        "1|1": {
            "PRIORITY": "55", 
            "IP_TYPE": "ipv4any", 
            "SRC_IP": "10.10.0.26/32", 
            "PACKET_ACTION": "forward", 
            "DST_IP": "10.10.1.26/32"
        }, 
        "3|1": {
            "PRIORITY": "55", 
            "IP_TYPE": "ipv6any", 
            "SRC_IPV6": "2001:0:3238:DFE1:63:0:0:FEFB/128", 
            "PACKET_ACTION": "forward", 
            "DST_IPV6": "3001:0:3238:DFE1:63:0:0:FEFB/128"
        }
    },
```

Now, did config reload and observed that  ACL rules are configured by verifying show acl rule.

```
root@sonic-testing:/home/admin# show acl rule
Table    Rule    Priority    Action    Match
-------  ------  ----------  --------  ------------------------------------------
1        1       55          forward   DST_IP: 10.10.1.26/32
                                       IP_TYPE: ipv4any
                                       SRC_IP: 10.10.0.26/32
3        1       55          forward   DST_IPV6: 3001:0:3238:DFE1:63:0:0:FEFB/128
                                       IP_TYPE: ipv6any
                                       SRC_IPV6: 2001:0:3238:DFE1:63:0:0:FEFB/128
```

After that tried to verify the ACL table using show acl table, but observed error

```
root@sonic-testing:/home/admin# show acl table
Traceback (most recent call last):
  File "/usr/bin/acl-loader", line 9, in <module>
    load_entry_point('sonic-utilities==1.2', 'console_scripts', 'acl-loader')()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/acl_loader/main.py", line 616, in table
    acl_loader.show_table(table_name)
  File "/usr/lib/python2.7/dist-packages/acl_loader/main.py", line 502, in show_table
    ports.sort(key=lambda name:int(name.strip('Ethernet')))
  File "/usr/lib/python2.7/dist-packages/acl_loader/main.py", line 502, in <lambda>
    ports.sort(key=lambda name:int(name.strip('Ethernet')))
ValueError: invalid literal for int() with base 10: 'Vlan500'
```

Let me know if my configuration is wrong. If my configuration is wrong, SONiC should not pass config reload with out error. As per the error, I understood the "show acl table" command parses the ports by stripping the "Ethernet" string and fetching the integer value from each port in the list. If VLAN is supported this needs to be changed.

Did ACL with VLAN is supported ? If so, please resolve this issue.

Attached is my config_db.json file used.
[config_db_vlan_acl.txt](https://github.com/Azure/SONiC/files/2518088/config_db_vlan_acl.txt)

**Comment by keboliu** [comment]
AFAIK ACL not supported on VLAN, check the code here:
https://github.com/Azure/sonic-swss/blob/master/orchagent/aclorch.cpp#L1077
Only support LAG and PORT.

**Comment by stcheng** [comment]
Yes. Right now VLAN is to be supported.

**Comment by chaitanc** [comment]
If VLAN is not supported then application should throw an error during the configuration itself, but getting python Exception while fetching acl table entries will convey it as an issue in the code not as unsupported.

**Comment by stcheng** [comment]
agree. we will try to enhance this in the `orchagent/aclorch.cpp` code
