### ISSUE TITLE
Config reload is stuck for long time after ValueError: or any syntactical error in config_db.json

### ISSUE THREAD

**Issue by chaitanc** [Azure/SONiC#279]
During my configuration in config_db.json I did a JSON syntactical error (Not intentionally) like leaving tailing "," at the end of the config_db.json,
```
"MGMT_INTERFACE": {
        "eth0|10.130.82.52/25": {
            "gwaddr": "10.130.82.1"
        }
    },
```
then did config reload -y observed below error. Which is expected.
```
root@sonic-testing:/home/admin# config reload -y
Running command: systemctl stop dhcp_relay
Running command: systemctl stop swss
Running command: systemctl stop snmp
Warning: Stopping snmp.service, but it can still be activated by:
  snmp.timer
  nning command: systemctl stop lldp
Running command: systemctl stop pmon
Running command: systemctl stop bgp
Running command: systemctl stop teamd
Running command: sonic-cfggen -j /etc/sonic/config_db.json --write-to-db
Traceback (most recent call last):
  File "/usr/local/bin/sonic-cfggen", line 263, in <module>
    main()
  File "/usr/local/bin/sonic-cfggen", line 210, in main
    deep_update(data, FormatConverter.to_deserialized(json.load(stream)))
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 615 column 1 (char 20540)
```

I corrected JSON format and did config reload again. Observed that config reload is not completed even after 1 hour. So I Interrupted the execution using CTRL + C.
```
root@sonic-testing:/home/admin# config reload -y
Running command: systemctl stop dhcp_relay
Running command: systemctl stop swss
Running command: systemctl stop snmp
Warning: Stopping snmp.service, but it can still be activated by:
  snmp.timer
Running command: systemctl stop lldp
Running command: systemctl stop pmon
Running command: systemctl stop bgp
Running command: systemctl stop teamd



^C
Aborted!
```

config reload is successfully executing only after rebooting the device which should not happen.

**Comment by Anandaraj-Maharajan** [comment]
Hi Chaitanya, 
Whenever loading config gets errored out due to a mistake, correct the mistake, execute the below command before trying config reload

redis-cli -n 4 SET CONFIG_DB_INITIALIZED true
