### ISSUE TITLE
Show command is not working with the new image on AG9032V1

### ISSUE THREAD

**Issue by Mahantinag** [Azure/SONiC#295]
Description:
========
Show command is not working with the new image on switch AG9032V1

Procedure:
=======

1. Install new image on AG9032V1,
2. Reboot switch after installation.
3. login as admin and try to run show commands.
4. Show commands not working.

Show command output:
===============

admin@sonic:~$ sudo su
root@sonic:/home/admin# show hardware
port_dict is None!
Traceback (most recent call last):
  File "/usr/bin/show", line 9, in <module>
    load_entry_point('sonic-utilities==1.2', 'console_scripts', 'show')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 199, in <module>
    iface_alias_converter = InterfaceAliasConverter()
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 60, in __init__
    raise click.Abort()
root@sonic:/home/admin# show bootware
port_dict is None!
Traceback (most recent call last):
  File "/usr/bin/show", line 9, in <module>
    load_entry_point('sonic-utilities==1.2', 'console_scripts', 'show')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 199, in <module>
    iface_alias_converter = InterfaceAliasConverter()
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 60, in __init__
    raise click.Abort()
click.exceptions.Abort
root@sonic:/home/admin# show clock
port_dict is None!
Traceback (most recent call last):
  File "/usr/bin/show", line 9, in <module>
    load_entry_point('sonic-utilities==1.2', 'console_scripts', 'show')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 199, in <module>
    iface_alias_converter = InterfaceAliasConverter()
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 60, in __init__
    raise click.Abort()
click.exceptions.Abort
root@sonic:/home/admin#

**Comment by Mahantinag** [comment]
[console_log_sonic_AG9032V1.txt](https://github.com/Azure/SONiC/files/2619424/console_log_sonic_AG9032V1.txt)
[syslog_sonic_AG9032V1.txt](https://github.com/Azure/SONiC/files/2619427/syslog_sonic_AG9032V1.txt)

**Comment by Mahantinag** [comment]
Attached syslog and console log for reference.

**Comment by Mahantinag** [comment]
sorry closed by mistake. reopening.

**Comment by chaitanc** [comment]
After looking in to this error, we debug to some extent and observed that config_db.json is empty by default. We tried to add config_db.json, but interfaces are not coming up.

Observed the same issue on AG9032, AS5712 , T7032-IX1B devices. Let us know, what is causing the issue and how to resolve it.

Tried uninstalling / installing OS for multiple times, but issue not resolved.

**Comment by chaitanc** [comment]
By debugging more from our side, we observed that this might be an issue with our hardware. Will close this issue once we confirms and resolve the issue.

**Comment by chaitanc** [comment]
In addition to my previous comment, issue is resolved. Root cause of the issue is older version of ONIE. Once we upgrade the ONIE and load the SONiC build worked fine.
