### ISSUE TITLE
"show" command python exception with SONiC-OS-HEAD.816

### ISSUE THREAD

**Issue by Kassec** [Azure/SONiC#317]
Hello,

First try with Sonic and I get this error with "show":
admin@sonic:~$ show
port_dict is None!
Traceback (most recent call last):
  File "/usr/bin/show", line 9, in <module>
    load_entry_point('sonic-utilities==1.2', 'console_scripts', 'show')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 202, in <module>
    iface_alias_converter = InterfaceAliasConverter()
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 60, in __init__
    raise click.Abort()
click.exceptions.Abort

More info:
admin@sonic:~$ uname -a
Linux sonic 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2015-12-19) x86_64 GNU/Linux
admin@sonic:~$ sudo sonic_installer list
Current: SONiC-OS-HEAD.816-f110d03
Next: SONiC-OS-HEAD.816-f110d03
Available:
SONiC-OS-HEAD.816-f110d03

Any help welcome ;)

**Comment by stcheng** [comment]
the error message is `port_dict is None!`. could you share what platform you are using?

**Comment by Kassec** [comment]
Sorry for missing this: sonic-broadcom.
I noticed also that "ip li" was not showing ports interfaces except the management one as well. Could it be related ?

**Comment by Kassec** [comment]
This may have something to do with platform not supported by SONiC:
```
onie_platform=x86_64-cel_redstone_xp-r0
onie_machine=cel_redstone_xp
onie_machine_rev=0
onie_arch=x86_64
```
