### ISSUE TITLE
SONiC201811  show python exception

### ISSUE THREAD

**Issue by knightswim** [Azure/SONiC#374]
After we adapted the SONiC201811 platform based on barefoot, we found that the show command reported an error and the error was as follows:
Admin@PHONEX-ALI-SPINE-1:~$ show
Port_dict is None!
Traceback (most recent call last):
  File "/usr/bin/show", line 9, in <module>
    Load_entry_point('sonic-utilities==1.2', 'console_scripts', 'show')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    Return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    Return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    Return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    Module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 204, in <module>
    Iface_alias_converter = InterfaceAliasConverter()
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 62, in __init__
    Raise click.Abort()
click.exceptions.Abort

**Comment by jochenschniepp-stordis** [comment]
I had a similar behavior last week on BRCM hardware and it turned out I must have corrupted config_db.json by a manual merge from console. After another clean install the 
switch was working fine and I was able to reproduce the same issue by creating another corrupt config_db.json and after rolling back to inital config_db.json provided by clean install, show commands were working fine again.

**Comment by knightswim** [comment]
Thank you very much for your help. I have solved this problem and it is really caused by the configuration
