### ISSUE TITLE
2kmac capacity table item show MAC more than 5 minutes, failed to show, need to be optimized

### ISSUE THREAD

**Issue by tim-rj** [Azure/SONiC#403]
# 2k mac table item show MAC more than 5 minutes, failed to show, need to be optimized
# 
![图片](https://user-images.githubusercontent.com/51427706/59437630-830aca00-8e24-11e9-865e-7ff3b304d481.png)

1、The network deploy  ebgp
2、TC1、TC2、TC5 Each devices sends 1k routes
3、TC1、TC2、TC5 the network fullmesh flow
## 
【06-14-14:05:03】root@LA1:/home/a# show arp
【06-14-14:05:03】Command: /usr/sbin/arp -n
【06-14-14:05:03】Address                  HWtype  HWaddress           Flags Mask            Iface
【06-14-14:05:03】172.31.104.101           ether   58:69:6c:83:56:85   C                     eth0
【06-14-14:05:03】20.1.0.3                 ether   00:10:94:00:00:12   C                     Ethernet47
【06-14-14:05:03】20.1.0.4                 ether   00:10:94:00:00:13   C                     Ethernet47
【06-14-14:05:03】3.3.3.1                  ether   58:69:6c:2d:30:25   C                     PortChannel0
【06-14-14:05:03】10.0.0.97                        (incomplete)                              PortChannel3
【06-14-14:05:03】10.0.0.111               ether   58:69:6c:2d:30:4f   C                     PortChannel4
【06-14-14:05:03】20.1.0.2                 ether   00:10:94:00:00:11   C                     Ethernet47
【06-14-14:05:03】172.31.104.1             ether   58:69:6c:14:b4:a7   C                     eth0
【06-14-14:05:03】
【06-14-14:05:50】root@LA1:/home/a# con
【06-14-14:05:50】config       config_data  continue     
【06-14-14:05:59】root@LA1:/home/a# config interface shutdown Ethernet60
【06-14-14:06:10】root@LA1:/home/a# show mac
【06-14-14:06:10】Command: fdbshow
【06-14-14:11:05】^CTraceback (most recent call last):                   ---------------more then 5 min
【06-14-14:11:05】  File "/usr/bin/fdbshow", line 145, in <module>
【06-14-14:11:05】    main()
【06-14-14:11:05】  File "/usr/bin/fdbshow", line 138, in main
【06-14-14:11:05】
【06-14-14:11:05】    fdb = FdbShow()
【06-14-14:11:05】  File "/usr/bin/fdbshow", line 47, in __init__
【06-14-14:11:05】Aborted!
【06-14-14:11:05】    self.fetch_fdb_data()
【06-14-14:11:05】  File "/usr/bin/fdbshow", line 83, in fetch_fdb_data
【06-14-14:11:05】    vlan_id = port_util.get_vlan_id_from_bvid(self.db, fdb["bvid"])
【06-14-14:11:05】  File "/usr/local/lib/python2.7/dist-packages/swsssdk/port_util.py", line 94, in get_vlan_id_from_bvid
【06-14-14:11:05】    db.connect('ASIC_DB')
【06-14-14:11:05】  File "/usr/local/lib/python2.7/dist-packages/swsssdk/interface.py", line 189, in connect
【06-14-14:11:05】    self._persistent_connect(db_name)
【06-14-14:11:05】  File "/usr/local/lib/python2.7/dist-packages/swsssdk/interface.py", line 213, in _persistent_connect
【06-14-14:11:05】    self._onetime_connect(db_name)
【06-14-14:11:05】  File "/usr/local/lib/python2.7/dist-packages/swsssdk/interface.py", line 204, in _onetime_connect
【06-14-14:11:05】    client.config_set('notify-keyspace-events', self.KEYSPACE_EVENTS)
【06-14-14:11:05】  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 719, in config_set
【06-14-14:11:05】    return self.execute_command('CONFIG SET', name, value)
【06-14-14:11:05】  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 667, in execute_command
【06-14-14:11:05】    connection.send_command(*args)
【06-14-14:11:05】  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 610, in send_command
【06-14-14:11:05】    self.send_packed_command(self.pack_command(*args))
【06-14-14:11:05】  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 585, in send_packed_command
【06-14-14:11:05】    self.connect()
【06-14-14:11:05】  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 493, in connect
【06-14-14:11:05】    self.on_connect()
【06-14-14:11:05】  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 567, in on_connect
【06-14-14:11:05】    if nativestr(self.read_response()) != 'OK':
【06-14-14:11:05】  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 624, in read_response
【06-14-14:11:05】    response = self._parser.read_response()
【06-14-14:11:05】  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 325, in read_response
【06-14-14:11:05】    if isinstance(response, bytes):
【06-14-14:11:05】KeyboardInterrupt

【06-14-14:04:37】root@LA1:/home/a# bcmcmd "l2 show" |wc -l
【06-14-14:04:38】32771

**Comment by prsunny** [comment]
it is supposed to be fixed as part of this [PR](https://github.com/Azure/sonic-utilities/pull/529)

**Comment by tim-rj** [comment]
> 
> 
> it is supposed to be fixed as part of this [PR](https://github.com/Azure/sonic-utilities/pull/529)

ok， good
