### ISSUE TITLE
make configure PLATFORM=broadcom fails

### ISSUE THREAD

**Issue by ehsnsbn** [Azure/SONiC#405]
Hi,
i am using ubuntu 16.04 on virtual machine, using the master source code.
it stuck at processing triggers for dbus. to solve it, on a new terminal i removed dbus, then applied sudo apt-get  upgrade! then the procedure stops here: how to solve it?

Step 15/37 : RUN pip3 install mockredispy==2.9.3
 ---> Running in 7597dac039ce
Collecting mockredispy==2.9.3
  Downloading https://files.pythonhosted.org/packages/0a/f1/d7db33898151aa9a1d647654cac55d01a5a1302fa4244af5fb5d3021f848/mockredispy-2.9.3.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/nose/: [Errno 0] Error -- Some packages may not be found!
    Couldn't find index page for 'nose' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [Errno 0] Error -- Some packages may not be found!
    No local packages or working download links found for nose
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-d95my2rj/mockredispy/setup.py", line 29, in <module>
        'with_redis = mockredis.noseplugin:WithRedis'
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 317, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 372, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 846, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1118, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1130, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 440, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 693, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('nose')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d95my2rj/mockredispy/
The command '/bin/sh -c pip3 install mockredispy==2.9.3' returned a non-zero code: 1
Makefile.work:133: recipe for target 'configure' failed
make[1]: *** [configure] Error 1
make[1]: Leaving directory '/home/sonic/sonic-buildimage'
Makefile:19: recipe for target 'configure' failed
make: *** [configure] Error 2****

**Comment by jleveque** [comment]
Modifying the packages on your host system shouldn't have any effect, because the build process is installing those packages in the slave Docker container where the image build will eventually take place.

This appears to be caused by a failure to download a Python package ("nose"). This may be transient PyPI server or network issue. Try the build again in a few hours. Reply with your results.

**Comment by ehsnsbn** [comment]
thank you Joe,
i will try again, and will reply with the result.
just a quick question: i am using ubuntu desktop 16.04-5 LTS in my
virtual-box.
am i using a right OS and environment?
is it mandatory to have HTTP/HTTPS proxy?

thank you!

**Comment by ehsnsbn** [comment]
hello dear Joe,
that problem passed.
now the new error. i am using squid as proxy server in my host machine.













*Removing intermediate container 066af1d9edd3 ---> 37e2371c49a4Step 33/37 :
RUN curl -fsSL https://download.docker.com/linux/debian/gpg
<https://download.docker.com/linux/debian/gpg> | sudo apt-key add - --->
Running in da841da696a5curl: (35) error:140770FC:SSL
routines:SSL23_GET_SERVER_HELLO:unknown protocolWarning: apt-key output
should not be parsed (stdout is not a terminal)gpg: no valid OpenPGP data
found.The command '/bin/sh -c curl -fsSL
https://download.docker.com/linux/debian/gpg
<https://download.docker.com/linux/debian/gpg> | sudo apt-key add -'
returned a non-zero code: 2Makefile.work:133: recipe for target 'configure'
failedmake[1]: *** [configure] Error 2make[1]: Leaving directory
'/home/sonic/Downloads/sonic-buildimage'Makefile:19: recipe for target
'configure' failedmake: *** [configure] Error 2*

**Comment by ehsnsbn** [comment]
hello,

finally, make configure is successfully done!
the solution was: for the https_proxy, i used http prefix!
thank you for your support! :)

Successfully built b26fb4e7e10d
Successfully tagged sonic-slave-stretch-sonic:latest
SONiC Build System

Build Configuration
"CONFIGURED_PLATFORM"             : "broadcom"
"SONIC_CONFIG_PRINT_DEPENDENCIES" : ""
"SONIC_BUILD_JOBS"                : "1"
"SONIC_CONFIG_MAKE_JOBS"          : "2"
"USERNAME"                        : "admin"
"PASSWORD"                        : "YourPaSsWoRd"
"ENABLE_DHCP_GRAPH_SERVICE"       : ""
"SHUTDOWN_BGP_ON_START"           : ""
"ENABLE_PFCWD_ON_START"           : ""
"INSTALL_DEBUG_TOOLS"             : ""
"ROUTING_STACK"                   : "frr"
"FRR_USER_UID"                    : "300"
"FRR_USER_GID"                    : "300"
"ENABLE_SYNCD_RPC"                : ""
"ENABLE_ORGANIZATION_EXTENSIONS"  : "y"
"HTTP_PROXY"                      : "http://192.168.1.38:3128/"
**"HTTPS_PROXY"                     : "http://192.168.1.38:3128/"**
"ENABLE_SYSTEM_TELEMETRY"         : "y"
"SONIC_DEBUGGING_ON"              : ""
"SONIC_PROFILING_ON"              : ""
"KERNEL_PROCURE_METHOD"           : "build"
"BUILD_TIMESTAMP"                 : "20190618.084452"
"BLDENV"                          : "stretch"
"VS_PREPARE_MEM"                  : "yes"

make[1]: Leaving directory '/home/sonic/Downloads/sonic-buildimage'

**Comment by kattamamatha** [comment]
I am facing this issue while executing make configure PLATFROM=broadcom

Step 15/37 : RUN pip3 install mockredispy==2.9.3
 ---> Running in 02b4b51e7122
Collecting mockredispy==2.9.3
  Downloading https://files.pythonhosted.org/packages/0a/f1/d7db33898151aa9a1d647654cac55d01a5a1302fa4244af5fb5d3021f848/mockredispy-2.9.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
        h.request(req.get_method(), req.selector, req.data, headers)
      File "/usr/lib/python3.5/http/client.py", line 1107, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
        self.endheaders(body)
      File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
        self._send_output(message_body)
      File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
        self.send(msg)
      File "/usr/lib/python3.5/http/client.py", line 877, in send
        self.connect()
      File "/usr/lib/python3/dist-packages/setuptools/ssl_support.py", line 190, in connect
        sock, cert_reqs=ssl.CERT_REQUIRED, ca_certs=self.ca_bundle
      File "/usr/lib/python3.5/ssl.py", line 1077, in wrap_socket
        ciphers=ciphers)
      File "/usr/lib/python3.5/ssl.py", line 760, in __init__
        self.do_handshake()
      File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
        self._sslobj.do_handshake()
      File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
        self._sslobj.do_handshake()
    ConnectionResetError: [Errno 104] Connection reset by peer
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 747, in open_url
        return open_with_auth(url, self.opener)
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 948, in _socket_timeout
        return func(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 1067, in open_with_auth
        fp = opener(request)
      File "/usr/lib/python3.5/urllib/request.py", line 466, in open
        response = self._open(req, data)
      File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
        '_open', req)
      File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
        result = func(*args)
      File "/usr/lib/python3/dist-packages/setuptools/ssl_support.py", line 161, in https_open
        lambda host, **kw: VerifyingHTTPSConn(host, self.ca_bundle, **kw), req
      File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jtq1ahsu/mockredispy/setup.py", line 29, in <module>
        'with_redis = mockredis.noseplugin:WithRedis'
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 317, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 372, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 846, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1118, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1130, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 440, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 687, in easy_install
        not self.always_copy, self.local_index
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 636, in fetch_distribution
        dist = find(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 617, in find
        dist.download_location = self.download(dist.location, tmpdir)
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 566, in download
        found = self._download_url(scheme.group(1), spec, tmpdir)
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 805, in _download_url
        return self._attempt_download(url, filename)
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 811, in _attempt_download
        headers = self._download_to(url, filename)
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 710, in _download_to
        fp = self.open_url(strip_fragment(url))
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 761, in open_url
        % (url, v.reason))
    distutils.errors.DistutilsError: Download error for https://files.pythonhosted.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz#sha256=f1bffef9cbc82628f6e7d7b40d7e255aefaa1adb6a1b1d26c69a8b79e6208a98: [Errno 104] Connection reset by peer
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jtq1ahsu/mockredispy/
The command '/bin/sh -c pip3 install mockredispy==2.9.3' returned a non-zero code: 1
Makefile.work:138: recipe for target 'configure' failed
make[1]: *** [configure] Error 1
make[1]: Leaving directory '/sonic-buildimage'
Makefile:19: recipe for target 'configure' failed
make: *** [configure] Error 2

**Comment by kattamamatha** [comment]
@ehsnsbn 
Have you cloned master or recent branch of sonic-buildimage from github repo.
