### ISSUE TITLE
syncd crashes during LAG flapping test

### ISSUE THREAD

**Issue by stcheng** [Azure/SONiC#47]
Will paste the core dump here.

**Comment by stcheng** [comment]
```
#0  0x00007f911d58d067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f911d58e448 in __GI_abort () at abort.c:89
#2  0x00007f911de7ab3d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f911de78bb6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f911de78c01 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f911de78e19 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f911e9a4fe7 in swss::RedisSelect::readMe() () from /usr/lib/x86_64-linux-gnu/libswsscommon.so.0
#7  0x00007f911e9a1237 in swss::Select::select(swss::Selectable**, int*, unsigned int) () from /usr/lib/x86_64-linux-gnu/libswsscommon.so.0
#8  0x0000000000406eff in ?? ()
#9  0x00007f911d579b45 in __libc_start_main (main=0x4069b0, argc=3, argv=0x7ffedac8af78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffedac8af68) at libc-start.c:287
#10 0x0000000000407d5d in ?? ()

```

**Comment by stcheng** [comment]
terminate called after throwing an instance of 'char const*'

**Comment by lguohan** [comment]
@stcheng, any update on this issue?
