### ISSUE TITLE
AS7816-64X can't setup breakout cable

### ISSUE THREAD

**Issue by titanlock** [Azure/SONiC#492]
I am unable to setup use for my breakout cables. I am following this guide here: https://github.com/Azure/SONiC/wiki/How-to-breakout-a-port, but noticed that the file is very different from the one an Accton uses like the index and the alias. i continue to get this python error (down below) after trying to reload the minigraph.

```
admin@unicycle-edgecore2:~$ sudo config load_minigraph -y
Stopping service swss ...
Stopping service lldp ...
Stopping service pmon ...
Stopping service bgp ...
Stopping service hostcfgd ...
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json --write-to-db
Traceback (most recent call last):
  File "/usr/local/bin/sonic-cfggen", line 294, in <module>
    main()
  File "/usr/local/bin/sonic-cfggen", line 223, in main
    deep_update(data, parse_xml(minigraph, platform))
  File "/usr/local/lib/python2.7/dist-packages/minigraph.py", line 512, in parse_xml
    root = ET.parse(filename).getroot()
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:81110)
  File "src/lxml/parser.pxi", line 1811, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:117841)
  File "src/lxml/parser.pxi", line 1837, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:118188)
  File "src/lxml/parser.pxi", line 1741, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:117100)
  File "src/lxml/parser.pxi", line 1138, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:111646)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)
  File "src/lxml/parser.pxi", line 633, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105621)
IOError: Error reading file '/etc/sonic/minigraph.xml': failed to load external entity "/etc/sonic/minigraph.xml"
```
Here is /usr/share/sonic/device/x86_64-accton_as7816_64x-r0/Accton-AS7816-64X/port_config.ini:
```
# name          lanes                 alias             index  speed
Ethernet0       73                    hundredGigE1      1      10000
Ethernet1       74                    hundredGigE1      1      10000
Ethernet2       75                    hundredGigE1      1      10000
Ethernet3       76                    hundredGigE1      1      10000
Ethernet4       65,66,67,68           hundredGigE2      2      100000
Ethernet8       81,82,83,84           hundredGigE3      3      100000
Ethernet12      89,90,91,92           hundredGigE4      4      100000
Ethernet16      105,106,107,108       hundredGigE5      5      100000
Ethernet20      97,98,99,100          hundredGigE6      6      100000
Ethernet24      113,114,115,116       hundredGigE7      7      100000
Ethernet28      121,122,123,124       hundredGigE8      8      100000
Ethernet32      41,42,43,44           hundredGigE9      9      100000
Ethernet36      33,34,35,36           hundredGigE10     10     100000
Ethernet40      49,50,51,52           hundredGigE11     11     100000
Ethernet44      57,58,59,60           hundredGigE12     12     100000
Ethernet48      137,138,139,140       hundredGigE13     13     100000
Ethernet52      129,130,131,132       hundredGigE14     14     100000
Ethernet56      145,146,147,148       hundredGigE15     15     100000
Ethernet60      153,154,155,156       hundredGigE16     16     100000
Ethernet64      173,174,175,176       hundredGigE17     17     100000
Ethernet68      165,166,167,168       hundredGigE18     18     100000
Ethernet72      181,182,183,184       hundredGigE19     19     100000
Ethernet76      189,190,191,192       hundredGigE20     20     100000
Ethernet80      13,14,15,16           hundredGigE21     21     100000
Ethernet84      5,6,7,8               hundredGigE22     22     100000
Ethernet88      29,30,31,32           hundredGigE23     23     100000
Ethernet92      21,22,23,24           hundredGigE24     24     100000
Ethernet96      205,206,207,208       hundredGigE25     25     100000
Ethernet100     197,198,199,200       hundredGigE26     26     100000
Ethernet104     213,214,215,216       hundredGigE27     27     100000
Ethernet108     221,222,223,224       hundredGigE28     28     100000
Ethernet112     229,230,231,232       hundredGigE29     29     100000
Ethernet116     237,238,239,240       hundredGigE30     30     100000
Ethernet120     245,246,247,248       hundredGigE31     31     100000
Ethernet124     253,254,255,256       hundredGigE32     32     100000
Ethernet128     69,70,71,72           hundredGigE33     33     100000
Ethernet132     77,78,79,80           hundredGigE34     34     100000
Ethernet136     93,94,95,96           hundredGigE35     35     100000
Ethernet140     85,86,87,88           hundredGigE36     36     100000
Ethernet144     101,102,103,104       hundredGigE37     37     100000
Ethernet148     109,110,111,112       hundredGigE38     38     100000
Ethernet152     125,126,127,128       hundredGigE39     39     100000
Ethernet156     117,118,119,120       hundredGigE40     40     100000
Ethernet160     37,38,39,40           hundredGigE41     41     100000
Ethernet164     45,46,47,48           hundredGigE42     42     100000
Ethernet168     61,62,63,64           hundredGigE43     43     100000
Ethernet172     53,54,55,56           hundredGigE44     44     100000
Ethernet176     133,134,135,136       hundredGigE45     45     100000
Ethernet180     141,142,143,144       hundredGigE46     46     100000
Ethernet184     157,158,159,160       hundredGigE47     47     100000
Ethernet188     149,150,151,152       hundredGigE48     48     100000
Ethernet192     161,162,163,164       hundredGigE49     49     100000
Ethernet196     169,170,171,172       hundredGigE50     50     100000
Ethernet200     185,186,187,188       hundredGigE51     51     100000
Ethernet204     177,178,179,180       hundredGigE52     52     100000
Ethernet208     1,2,3,4               hundredGigE53     53     100000
Ethernet212     9,10,11,12            hundredGigE54     54     100000
Ethernet216     25,26,27,28           hundredGigE55     55     100000
Ethernet220     17,18,19,20           hundredGigE56     56     100000
Ethernet224     193,194,195,196       hundredGigE57     57     100000
Ethernet228     201,202,203,204       hundredGigE58     58     100000
Ethernet232     217,218,219,220       hundredGigE59     59     100000
Ethernet236     209,210,211,212       hundredGigE60     60     100000
Ethernet240     225,226,227,228       hundredGigE61     61     100000
Ethernet244     233,234,235,236       hundredGigE62     62     100000
Ethernet248     249,250,251,252       hundredGigE63     63     100000
Ethernet252     241,242,243,244       hundredGigE64     64     100000
```
Is there some other procedure I need to do for the AS7816-64X that the guide is not telling me?
Also Ethernet0 does have a breakout cable plugged into it. (In case you needed to know)

**Comment by pollyhsu2git** [comment]
@titanlock
Any info of your tested image? e.g.
$ show version

**Comment by titanlock** [comment]
Here is "show version"
```
SONiC Software Version: SONiC.master.0-dirty-20190917.135340
Distribution: Debian 9.11
Kernel: 4.9.0-9-2-amd64
Build commit: a62ab789
Build date: Tue Sep 17 18:48:53 UTC 2019
Built by: opnfv@sanic

Platform: x86_64-accton_as7816_64x-r0
HwSKU: Accton-AS7816-64X
ASIC: broadcom
Serial Number: 781664X1913014
Uptime: 00:19:09 up 1 day,  7:02,  1 user,  load average: 1.26, 1.26, 1.28

Docker images:
REPOSITORY                 TAG                              IMAGE ID            SIZE
docker-syncd-brcm          latest                           986dc56543e3        392MB
docker-syncd-brcm          master.0-dirty-20190917.135340   986dc56543e3        392MB
docker-fpm-frr             latest                           ae1ce79e3a9e        319MB
docker-fpm-frr             master.0-dirty-20190917.135340   ae1ce79e3a9e        319MB
docker-lldp-sv2            latest                           601f2ec15316        298MB
docker-lldp-sv2            master.0-dirty-20190917.135340   601f2ec15316        298MB
docker-dhcp-relay          latest                           b1a05d9ec50c        289MB
docker-dhcp-relay          master.0-dirty-20190917.135340   b1a05d9ec50c        289MB
docker-database            latest                           222c94f4656e        281MB
docker-database            master.0-dirty-20190917.135340   222c94f4656e        281MB
docker-snmp-sv2            latest                           38c6edb90437        334MB
docker-snmp-sv2            master.0-dirty-20190917.135340   38c6edb90437        334MB
docker-orchagent           latest                           fc47a59bc228        321MB
docker-orchagent           master.0-dirty-20190917.135340   fc47a59bc228        321MB
docker-sflow               latest                           ec6b61903b56        303MB
docker-sflow               master.0-dirty-20190917.135340   ec6b61903b56        303MB
docker-teamd               latest                           82f07268922c        302MB
docker-teamd               master.0-dirty-20190917.135340   82f07268922c        302MB
docker-sonic-telemetry     latest                           61c0839059b4        304MB
docker-sonic-telemetry     master.0-dirty-20190917.135340   61c0839059b4        304MB
docker-router-advertiser   latest                           5b2e854c8316        281MB
docker-router-advertiser   master.0-dirty-20190917.135340   5b2e854c8316        281MB
docker-platform-monitor    latest                           2010479446c5        326MB
docker-platform-monitor    master.0-dirty-20190917.135340   2010479446c5        326MB
```

**Comment by pollyhsu2git** [comment]
@titanlock 
After checking the SONiC build system, the build of 2019-09-17, commit ID: **a62ab789** **HAD** the **BUILD FAILURE** (https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-all/82).
We'll suggest you to choose another one which was build PASSed to try.

**Comment by titanlock** [comment]
I am getting the same results with a PASSed build here is the Jenkins build: https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-all/98/

"show version"
```
SONiC Software Version: SONiC.HEAD.98-dirty-20191008.083913
Distribution: Debian 9.11
Kernel: 4.9.0-9-2-amd64
Build commit: 9726f6c0
Build date: Tue Oct  8 08:47:01 UTC 2019
Built by: johnar@jenkins-worker-3

Platform: x86_64-accton_as7816_64x-r0
HwSKU: Accton-AS7816-64X
ASIC: broadcom
Serial Number: 781664X1913008
Uptime: 04:25:27 up 0 min,  1 user,  load average: 2.56, 0.58, 0.19

Docker images:
REPOSITORY                 TAG                             IMAGE ID            SIZE
docker-syncd-brcm          HEAD.98-dirty-20191008.083913   3aa94fa9847b        391MB
docker-syncd-brcm          latest                          3aa94fa9847b        391MB
docker-lldp-sv2            HEAD.98-dirty-20191008.083913   89937c22d8c7        298MB
docker-lldp-sv2            latest                          89937c22d8c7        298MB
docker-router-advertiser   HEAD.98-dirty-20191008.083913   316f67dfebcc        281MB
docker-router-advertiser   latest                          316f67dfebcc        281MB
docker-dhcp-relay          HEAD.98-dirty-20191008.083913   747e689dbfce        289MB
docker-dhcp-relay          latest                          747e689dbfce        289MB
docker-database            HEAD.98-dirty-20191008.083913   4f614e2d0997        280MB
docker-database            latest                          4f614e2d0997        280MB
docker-sflow               HEAD.98-dirty-20191008.083913   246e7e06402e        302MB
docker-sflow               latest                          246e7e06402e        302MB
docker-teamd               HEAD.98-dirty-20191008.083913   976cc87624c9        302MB
docker-teamd               latest                          976cc87624c9        302MB
docker-snmp-sv2            HEAD.98-dirty-20191008.083913   95ac0e957f0e        334MB
docker-snmp-sv2            latest                          95ac0e957f0e        334MB
docker-orchagent           HEAD.98-dirty-20191008.083913   4a5c3d3e1422        320MB
docker-orchagent           latest                          4a5c3d3e1422        320MB
docker-fpm-frr             HEAD.98-dirty-20191008.083913   acbadb517b86        319MB
docker-fpm-frr             latest                          acbadb517b86        319MB
docker-sonic-telemetry     HEAD.98-dirty-20191008.083913   62619446c9b7        303MB
docker-sonic-telemetry     latest                          62619446c9b7        303MB
docker-platform-monitor    HEAD.98-dirty-20191008.083913   d9b4f28c6aa8        328MB
docker-platform-monitor    latest                          d9b4f28c6aa8        328MB

```

Another thing I noticed is that the containers are constantly receiving a SIGTERM if I try to manually setup the breakout cable in config_db.json, for example syncd below.

"docker logs syncd"
```
/usr/lib/python2.7/dist-packages/supervisor/options.py:298: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to sp
ecify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2016-11-22 13:54:59,365 CRIT Set uid to user 0
2016-11-22 13:54:59,365 INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2016-11-22 13:54:59,379 INFO RPC interface 'supervisor' initialized
2016-11-22 13:54:59,379 INFO supervisord started with pid 1
2016-11-22 13:55:00,381 INFO spawned: 'start.sh' with pid 8
2016-11-22 13:55:00,630 INFO spawned: 'rsyslogd' with pid 12
2016-11-22 13:55:01,632 INFO success: start.sh entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-11-22 13:55:01,633 INFO success: rsyslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-11-22 13:55:01,855 INFO spawned: 'syncd' with pid 19
2016-11-22 13:55:03,439 INFO success: syncd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-11-22 13:55:09,418 INFO spawned: 'ledinit' with pid 66
2016-11-22 13:55:09,419 INFO success: ledinit entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2016-11-22 13:55:09,432 INFO exited: start.sh (exit status 0; expected)
2016-11-22 13:55:09,443 INFO exited: ledinit (exit status 0; expected)
2016-11-22 13:55:14,619 INFO exited: syncd (exit status 0; expected)
2016-11-22 13:55:15,264 WARN received SIGTERM indicating exit request
2016-11-22 13:55:15,264 INFO waiting for rsyslogd to die
2016-11-22 13:55:17,269 INFO stopped: rsyslogd (exit status 0)
/usr/lib/python2.7/dist-packages/supervisor/options.py:298: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to sp
ecify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2016-11-22 13:56:07,589 CRIT Set uid to user 0
2016-11-22 13:56:07,589 INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2016-11-22 13:56:07,601 INFO RPC interface 'supervisor' initialized
2016-11-22 13:56:07,601 INFO supervisord started with pid 1
2016-11-22 13:56:08,603 INFO spawned: 'start.sh' with pid 13
2016-11-22 13:56:08,848 INFO spawned: 'rsyslogd' with pid 17
2016-11-22 13:56:09,849 INFO success: start.sh entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-11-22 13:56:09,850 INFO success: rsyslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-11-22 13:56:10,100 INFO spawned: 'syncd' with pid 24
2016-11-22 13:56:11,192 INFO success: syncd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-11-22 13:56:17,580 INFO spawned: 'ledinit' with pid 74
2016-11-22 13:56:17,580 INFO success: ledinit entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2016-11-22 13:56:17,597 INFO exited: start.sh (exit status 0; expected)
2016-11-22 13:56:17,608 INFO exited: ledinit (exit status 0; expected)
2016-11-22 13:56:21,472 INFO exited: syncd (exit status 0; expected)
2016-11-22 13:56:21,837 WARN received SIGTERM indicating exit request
2016-11-22 13:56:21,837 INFO waiting for rsyslogd to die
2016-11-22 13:56:23,842 INFO stopped: rsyslogd (exit status 0)
/usr/lib/python2.7/dist-packages/supervisor/options.py:298: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to sp
ecify a "-c" argument specifying an absolute path to a configuration file for improved security.
```

Here is what my manual setup for a breakout looks like in config_db.json, not sure if this is correct.
```
        "Ethernet24": {
            "admin_status": "up",
            "alias": "hundredGigE7",
            "index": "7",
            "lanes": "113",
            "mtu": "1500",
            "speed": "10000"
        },
        "Ethernet25": {
            "admin_status": "up",
            "alias": "hundredGigE7",
            "index": "65",
            "lanes": "114",
            "mtu": "1500",
            "speed": "10000"
        },
        "Ethernet26": {
            "admin_status": "up",
            "alias": "hundredGigE7",
            "index": "66",
            "lanes": "115",
            "mtu": "1500",
            "speed": "10000"
        },
        "Ethernet27": {
            "admin_status": "up",
            "alias": "hundredGigE7",
            "index": "67",
            "lanes": "116",
            "mtu": "1500",
            "speed": "10000"
        },
```

**Comment by titanlock** [comment]
Does anyone have any more info on this?

**Comment by pollyhsu2git** [comment]
@titanlock 
Was your port up OK at 100G?

**Comment by titanlock** [comment]
The cable does not support 100G, so I am not sure what you mean by this.
