### ISSUE TITLE
Wedge100bf-65x - not interfaces shown and sfpshow / sfputil broken in 574-dirty-20200221

### ISSUE THREAD

**Issue by maikpfeil** [Azure/SONiC#566]
Hello SONiC-Team,

we encountered an issue on a Wedge100BF-65x running latest (574-dirty-20200221) version from jenkins artifactory.  

It also didn't work in older release, tried also 20191219.

Freshly bootup with only change to mgmt interface configuration. 

admin@sonic:~$ sudo show version

SONiC Software Version: SONiC.HEAD.574-dirty-20200221.051443
Distribution: Debian 9.12
Kernel: 4.9.0-11-2-amd64
Build commit: 30ef1119
Build date: Fri Feb 21 07:45:27 UTC 2020
Built by: johnar@jenkins-worker-4

Platform: x86_64-accton_wedge100bf_65x-r0
HwSKU: mavericks
ASIC: barefoot
Device is not ready: initializing..
Serial Number:
Uptime: 14:30:27 up 22 min,  4 users,  load average: 0.27, 0.38, 0.40

Docker images:
REPOSITORY                    TAG                              IMAGE ID            SIZE
docker-syncd-bfn              HEAD.574-dirty-20200221.051443   35f692a815b3        1.77GB
docker-syncd-bfn              latest                           35f692a815b3        1.77GB
docker-router-advertiser      HEAD.574-dirty-20200221.051443   5bba01c678ab        288MB
docker-router-advertiser      latest                           5bba01c678ab        288MB
docker-sonic-mgmt-framework   HEAD.574-dirty-20200221.051443   ff0a74ffc102        425MB
docker-sonic-mgmt-framework   latest                           ff0a74ffc102        425MB
docker-platform-monitor       HEAD.574-dirty-20200221.051443   a845426392ec        340MB
docker-platform-monitor       latest                           a845426392ec        340MB
docker-fpm-frr                HEAD.574-dirty-20200221.051443   1b0c590d483b        332MB
docker-fpm-frr                latest                           1b0c590d483b        332MB
docker-sflow                  HEAD.574-dirty-20200221.051443   62ed5c465ec4        312MB
docker-sflow                  latest                           62ed5c465ec4        312MB
docker-lldp-sv2               HEAD.574-dirty-20200221.051443   db990f6d01db        309MB
docker-lldp-sv2               latest                           db990f6d01db        309MB
docker-dhcp-relay             HEAD.574-dirty-20200221.051443   0218a2afc2cc        298MB
docker-dhcp-relay             latest                           0218a2afc2cc        298MB
docker-database               HEAD.574-dirty-20200221.051443   1f272d99a4be        288MB
docker-database               latest                           1f272d99a4be        288MB
docker-snmp-sv2               HEAD.574-dirty-20200221.051443   9f67d361e7c9        345MB
docker-snmp-sv2               latest                           9f67d361e7c9        345MB
docker-orchagent              HEAD.574-dirty-20200221.051443   dda3ca20d653        330MB
docker-orchagent              latest                           dda3ca20d653        330MB
docker-teamd                  HEAD.574-dirty-20200221.051443   5b9ffa153ae9        312MB
docker-teamd                  latest                           5b9ffa153ae9        312MB
docker-nat                    HEAD.574-dirty-20200221.051443   48a28a3335ed        314MB
docker-nat                    latest                           48a28a3335ed        314MB
docker-sonic-telemetry        HEAD.574-dirty-20200221.051443   eb0ff191b489        349MB
docker-sonic-telemetry        latest                           eb0ff191b489        349MB

admin@sonic:~$
admin@sonic:~$
admin@sonic:~$
admin@sonic:~$ sudo show interfaces transceiver presence
Traceback (most recent call last):
  File "/usr/bin/sfpshow", line 358, in <module>
    cli()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/bin/sfpshow", line 355, in presence
    sfp.display_presence(port)
  File "/usr/bin/sfpshow", line 324, in display_presence
    for i in port_table_keys:
TypeError: 'NoneType' object is not iterable
admin@sonic:~$
admin@sonic:~$
admin@sonic:~$
admin@sonic:~$ sudo show interfaces status
admin@sonic:~$
admin@sonic:~$
admin@sonic:~$
admin@sonic:~$
admin@sonic:~$
admin@sonic:~$ sudo show interfaces description
admin@sonic:~$
admin@sonic:~$
admin@sonic:~$
admin@sonic:~$
admin@sonic:~$
admin@sonic:~$
admin@sonic:~$ sudo sfputil show presence
No handlers could be found for logger "thrift.transport.TSocket"
Traceback (most recent call last):
  File "/usr/bin/sfputil", line 12, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sfputil/main.py", line 481, in presence
    presence = platform_sfputil.get_presence(physical_port)
  File "/usr/share/sonic/device/x86_64-accton_wedge100bf_65x-r0/plugins/sfputil.py", line 105, in get_presence
    if port_num < self.port_start or port_num > self.port_end:
  File "/usr/share/sonic/device/x86_64-accton_wedge100bf_65x-r0/plugins/sfputil.py", line 41, in port_start
    self.update_port_info()
  File "/usr/share/sonic/device/x86_64-accton_wedge100bf_65x-r0/plugins/sfputil.py", line 80, in update_port_info
    self.thrift_setup()
  File "/usr/share/sonic/device/x86_64-accton_wedge100bf_65x-r0/plugins/sfputil.py", line 97, in thrift_setup
    transport.open()
  File "/usr/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 153, in open
    return self.__trans.open()
  File "/usr/lib/python2.7/dist-packages/thrift/transport/TSocket.py", line 113, in open
    raise TTransportException(TTransportException.NOT_OPEN, msg)
thrift.transport.TTransport.TTransportException: Could not connect to any of [('127.0.0.1', 9090)]
admin@sonic:~$

Do you have an idea where we can further debug this issue? 

Thank you! 

// Maik

**Comment by arkadiyshapiro** [comment]
Hi Maik,

Please file a case with support@barefootnetworks.com <mailto:support@barefootnetworks.com>  and we can help. Let me know when you file one or if things are not moving forward.

 

Arkadiy Shapiro

Product Line Manager, Core Software and Tech Partnerships

Barefoot Networks, an Intel Company

 <mailto:arkadiy.shapiro@intel.com> arkadiy.shapiro@intel.com / 408-410-3189

**Comment by rbone-mitre** [comment]
Hello, has any progress been made on this error? I'm experiencing something similar with HEAD.774
