### ISSUE TITLE
Mellanox SN2010 SFP EEPROM Not detected

### ISSUE THREAD

**Issue by Dscano** [Azure/SONiC#687]
Hi,

I have install SONiC on my Mellanox SN2010 switch. But I canno't see the information provided by the command  `show interfaces transceiver eeprom`
Thi is my SONiC version:
```
Current: SONiC-OS-master.424-f61ff95e
Next: SONiC-OS-master.424-f61ff95e
Available: 
SONiC-OS-master.424-f61ff95e
```
When I use the command `show interfaces transceiver eeprom Ethernet0 --dom` I get this error:
```
Usage: show interfaces transceiver eeprom [OPTIONS] [INTERFACENAME]
Try "show interfaces transceiver eeprom -h" for help.

Error: cannot find interface name for alias Ethernet0
```
If I use the command `show interfaces alias`:
```
Name        Alias
----------  ----------
Ethernet0   Ethernet0

```
And the command `-d /dev/mst/mt52100_pci_cr0  -p 1 --show_serdes_tx` show:
```
Operational Info
----------------
State                           : Active
Physical state                  : LinkUp
Speed                           : 10GbE
Width                           : 1x
FEC                             : No FEC
Loopback Mode                   : No Loopback
Auto Negotiation                : ON

Supported Info
--------------
Enabled Link Speed              : 0x00007010 (10G)
Supported Cable Speed           : 0x3c007011 (25G,10G,1G)

Troubleshooting Info
--------------------
Status Opcode                   : 0
Group Opcode                    : N/A
Recommendation                  : No issue was observed.

Serdes Tuning Transmitter Info
------------------------------
Serdes TX parameters            : Pol,tap0,tap1,tap2,bias,preemp_mode
Lane 0                          : 0,0,120,0,16,4
```
What I'm doing wrong? Why the SFP EEPROM is not detected ?

**Comment by Chornei** [comment]
Hi

We will verify with latest master available and update you on that.

Liat

**Comment by Dscano** [comment]
> Hi We will verify with latest master available and update you on that. Liat From: Dscano <notifications@github.com> Sent: Thursday, October 15, 2020 3:06 PM To: Azure/SONiC <SONiC@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Azure/SONiC] Mellanox SN2010 SFP EEPROM Not detected (#687) Hi, I have install SONiC on my Mellanox SN2010 switch. But I canno't see the information provided by the command show interfaces transceiver eeprom Thi is my SONiC version: Current: SONiC-OS-master.424-f61ff95e Next: SONiC-OS-master.424-f61ff95e Available: SONiC-OS-master.424-f61ff95e When I use the command show interfaces transceiver eeprom Ethernet0 --dom I get this error: Usage: show interfaces transceiver eeprom [OPTIONS] [INTERFACENAME] Try "show interfaces transceiver eeprom -h" for help. Error: cannot find interface name for alias Ethernet0 If I use the command show interfaces alias: Name Alias
> […](#)
> ---------- ---------- Ethernet0 Ethernet0 And the command -d /dev/mst/mt52100_pci_cr0 -p 1 --show_serdes_tx show: Operational Info
> ---------------- State : Active Physical state : LinkUp Speed : 10GbE Width : 1x FEC : No FEC Loopback Mode : No Loopback Auto Negotiation : ON Supported Info
> -------------- Enabled Link Speed : 0x00007010 (10G) Supported Cable Speed : 0x3c007011 (25G,10G,1G) Troubleshooting Info
> -------------------- Status Opcode : 0 Group Opcode : N/A Recommendation : No issue was observed. Serdes Tuning Transmitter Info
> ------------------------------ Serdes TX parameters : Pol,tap0,tap1,tap2,bias,preemp_mode Lane 0 : 0,0,120,0,16,4 What I'm doing wrong? Why the SFP EEPROM is not detected ? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FSONiC%2Fissues%2F687&data=04%7C01%7Cliatg%40nvidia.com%7Cb6f7b58e1e214c5efaa408d871045834%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637383610765497257%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=u5BXn5XB3gymd8S79k8yGlT3adBwv7Pah%2FMHcwhacNA%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEM2NC3FL7BZUZTJ3EOWYADSK3QSHANCNFSM4SR4V5YQ&data=04%7C01%7Cliatg%40nvidia.com%7Cb6f7b58e1e214c5efaa408d871045834%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637383610765507259%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PIG7GBdqbuSeJhQBalBrlql9Wh8eKCLiU7I5NsDTv00%3D&reserved=0>.

Hi,

Have you any news?

best regards

**Comment by keboliu** [comment]
could you please try the image from the 201911 branch (can try image with this hash: 5a802533b5c28b35063921019f06302034f6930f )?  On master we have a kernel patch PR not merged yet  https://github.com/Azure/sonic-linux-kernel/pull/162 .   or you can build a master image including this PR it should be OK.

**Comment by Dscano** [comment]
Hi keboliu,

I think that in both cases I get a Kernel module that I have to "install" in SONiC. Is it correct?
1)I clone the repo https://github.com/Azure/sonic-linux-kernel/tree/201911 and I followed the README and I get this error:
```
~/Desktop/SONiC_no_patch/sonic-linux-kernel/linux-4.19.118 ~/Desktop/SONiC_no_patch/sonic-linux-kernel
Initialized empty Git repository in /home/diaccio/Desktop/SONiC_no_patch/sonic-linux-kernel/linux-4.19.118/.git/
Checking for changes in the working directory ... done
Importing patch "packaging-update-abiname.patch" ... done
Now at patch "packaging-update-abiname.patch"
Traceback (most recent call last):
  File "debian/bin/gencontrol.py", line 682, in <module>
    Gencontrol()()
  File "/home/diaccio/Desktop/SONiC_no_patch/sonic-linux-kernel/linux-4.19.118/debian/bin/debian_linux/gencontrol.py", line 109, in __call__
    self.do_main(packages, makefile)
  File "/home/diaccio/Desktop/SONiC_no_patch/sonic-linux-kernel/linux-4.19.118/debian/bin/debian_linux/gencontrol.py", line 127, in do_main
    self.do_main_setup(vars, makeflags, extra)
  File "debian/bin/gencontrol.py", line 113, in do_main_setup
    env=kw_env)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'kernel-wedge'
Makefile:57: recipe for target '/linux-headers-4.19.0-9-2-common_4.19.118-2+deb10u1_all.deb' failed
make: *** [/linux-headers-4.19.0-9-2-common_4.19.118-2+deb10u1_all.deb] Error 1
''
```

2)

> in master we have a kernel patch PR not merged yet Azure/sonic-linux-kernel#162 . or you can build a master image including this PR it should be OK.

 how can I build the master image with this patch? sorry but is the first time that I use SONiC
