### ISSUE TITLE
Platform: x86_64-accton_as9716_32d-r0 issues on latest release build

### ISSUE THREAD

**Issue by dancelray** [Azure/SONiC#713]
**We do not triage issue for this repo. All issues are triaged in Azure/sonic-buildimage repo**

I am using this version but not able to detect transceiver, psustatus, fan and temperature.

admin@sonic:~$ show version

SONiC Software Version: SONiC.master.503-50387305
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: 50387305
Build date: Wed Nov 25 20:02:24 UTC 2020
Built by: johnar@jenkins-worker-6

Platform: x86_64-accton_as9716_32d-r0
HwSKU: Accton-AS9716-32D
ASIC: broadcom
Serial Number: 971632D2045009
Uptime: 03:49:20 up 17:30,  1 user,  load average: 0.29, 0.44, 0.44

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-teamd                  latest                f53e880dd938        486MB
docker-teamd                  master.503-50387305   f53e880dd938        486MB
docker-nat                    latest                bf1b3a5eacd8        489MB
docker-nat                    master.503-50387305   bf1b3a5eacd8        489MB
docker-router-advertiser      latest                73ab09994f47        443MB
docker-router-advertiser      master.503-50387305   73ab09994f47        443MB
docker-platform-monitor       latest                ffd8b7674311        566MB
docker-platform-monitor       master.503-50387305   ffd8b7674311        566MB
docker-lldp                   latest                b1d73b7f5402        517MB
docker-lldp                   master.503-50387305   b1d73b7f5402        517MB
docker-database               latest                9c718f365006        443MB
docker-database               master.503-50387305   9c718f365006        443MB
docker-orchagent              latest                d60bd396225d        500MB
docker-orchagent              master.503-50387305   d60bd396225d        500MB
docker-snmp                   latest                2e8076164752        479MB
docker-snmp                   master.503-50387305   2e8076164752        479MB
docker-dhcp-relay             latest                c656786fa126        450MB
docker-dhcp-relay             master.503-50387305   c656786fa126        450MB
docker-sonic-telemetry        latest                ba6b48895331        511MB
docker-sonic-telemetry        master.503-50387305   ba6b48895331        511MB
docker-sonic-mgmt-framework   latest                8d28abb4d95e        599MB
docker-sonic-mgmt-framework   master.503-50387305   8d28abb4d95e        599MB
docker-fpm-frr                latest                c757e71559f8        501MB
docker-fpm-frr                master.503-50387305   c757e71559f8        501MB
docker-sflow                  latest                4e7d290390c9        486MB
docker-sflow                  master.503-50387305   4e7d290390c9        486MB
docker-syncd-brcm             latest                e71ee746a8ed        541MB
docker-syncd-brcm             master.503-50387305   e71ee746a8ed        541MB

admin@sonic:~$ show interfaces transceiver eeprom
Ethernet0: SFP EEPROM Not detected

admin@sonic:~$ show platform syseeprom
TlvInfo Header:
   Id String:    TlvInfo
   Version:      1
   Total Length: 172
TLV Name             Code Len Value
-------------------- ---- --- -----
Manufacture Date     0x25  19 11/11/2020 13:07:49
Label Revision       0x27   4 R01A
Platform Name        0x28  27 x86_64-accton_as9716_32D-r0
ONIE Version         0x29  13 2019.08.00.03
Manufacturer         0x2B   6 Accton
Manufacture Country  0x2C   2 TW
Diag Version         0x2E  11 01.01.00.17
Base MAC Address     0x24   6 34:EF:B6:17:A2:C0
Serial Number        0x23  14 971632D2045009
Part Number          0x22  13 FP5ZZ8632006A
Product Name         0x21  15 9716-32D-O-AC-F
MAC Addresses        0x2A   2 256
Vendor Name          0x2D   8 Edgecore
CRC-32               0xFE   4 0x1129D349

admin@sonic:~$ show platform psustatus
Error! Failed to get the number of PSUs!
Error: fail to get psu status from state DB
 
admin@sonic:~$ show platform fan
Fan Not detected
 
admin@sonic:~$ show platform temperature
Thermal Not detected

**Comment by abhiranjeet** [comment]
Hi, I am facing the exact same issue. Were you able to figure this out ?

**Comment by zhengbiqing** [comment]
@dancelray did you fix your problem? I have almost the same problem:


2004l2004hzbq@sonic:~$ show platform syseeprom
2004lTraceback (most recent call last):
  File "/usr/local/bin/decode-syseeprom", line 18, in <module>
    import sonic_platform
ModuleNotFoundError: No module named 'sonic_platform'


2004hzbq@sonic:~$ show platform psustatus
2004lError: Failed to get the number of PSUs
Error: Failed to get PSU status
Error: failed to get PSU status from state DB


2004hzbq@sonic:~$ show platform psustatusfan 
2004lFan Not detected


2004hzbq@sonic:~$ show platform temperature 
2004lThermal Not detected


2004hzbq@sonic:~$ show platform syseeprom
2004lTraceback (most recent call last):
  File "/usr/local/bin/decode-syseeprom", line 18, in <module>
    import sonic_platform
ModuleNotFoundError: No module named 'sonic_platform'

**Comment by wally-wang-accton** [comment]
You can try master code.  We git clone 2/14/2022 code which can work well.
