### ISSUE TITLE
BGP docker crash after using invalid IP for VLAN interface

### ISSUE THREAD

**Issue by gcupryn** [Azure/SONiC#740]
Hi,
By accident I managed to crash  SONiC by using just invalid IP address, after applying this config:
```
admin@sonic:~$ cat vlan_intf_bgp_crash.json
{
    "VLAN": {
        "Vlan100": {
            "vlanid": 100
        }
    },

    "VLAN_INTERFACE": {
        "Vlan100|192.168.-1.1/24": {}
    }
}

```

/var/log/syslog contains:

```
`Jan 22 02:34:07.038488 sonic ERR swss#intfmgrd: :- main: Runtime error: Error converting 192.168.-1.1 to IP address
Jan 22 02:34:07.039460 sonic CRIT bgp#bgpcfgd: Got an exception 'interface': Traceback: Traceback (most recent call last):#012  File "/usr/local/bin/bgpcfgd", line 900, in <module>#012    main()#012  File "/usr/local/bin/bgpcfgd", line 885, in main#012    runner.run()#012  File "/usr/local/bin/bgpcfgd", line 232, in run#012    callback(key, op, dict(fvs))#012  File "/usr/local/bin/bgpcfgd", line 271, in handler#012    res = self.set_handler(key, data)#012  File "/usr/local/bin/bgpcfgd", line 356, in set_handler#012    log_warn("Subnet '%s' format is wrong for interface '%s'" % (network_str, data["interface"]))#012KeyError: 'interface'
Jan 22 02:34:07.051272 sonic INFO kernel: [ 8221.528340] 8021q: 802.1Q VLAN Support v1.8
Jan 22 02:34:07.051301 sonic INFO kernel: [ 8221.528352] 8021q: adding VLAN 0 to HW filter on device eth0
Jan 22 02:34:07.053684 sonic NOTICE swss#orchagent: :- addVlan: Create an empty VLAN Vlan100 vid:100
Jan 22 02:34:07.055267 sonic INFO kernel: [ 8221.529646] device Bridge entered promiscuous mode
Jan 22 02:34:07.055294 sonic INFO kernel: [ 8221.529797] IPv6: ADDRCONF(NETDEV_UP): Vlan100: link is not ready
Jan 22 02:34:08.045767 sonic INFO swss#supervisor-proc-exit-listener: Process intfmgrd exited unxepectedly. Terminating supervisor...
Jan 22 02:34:08.050078 sonic INFO bgp#supervisor-proc-exit-listener: Process bgpcfgd exited unxepectedly. Terminating supervisor...
Jan 22 02:34:08.100638 sonic INFO swss#supervisord 2021-01-22 02:34:07,039 INFO exited: intfmgrd (exit status 255; not expected)
Jan 22 02:34:08.100638 sonic INFO swss#supervisord 2021-01-22 02:34:08,045 WARN received SIGTERM indicating exit request
Jan 22 02:34:08.100638 sonic INFO swss#supervisord 2021-01-22 02:34:08,046 INFO waiting for vrfmgrd, buffermgrd, orchagent, portmgrd, vxlanmgrd, neighsyncd, portsyncd, vlanmgrd, nbrmgrd, supervisor-proc-exit-listener, rsyslogd to die
Jan 22 02:34:08.100638 sonic INFO swss#supervisord 2021-01-22 02:34:08,047 INFO stopped: vxlanmgrd (terminated by SIGTERM)
Jan 22 02:34:08.100638 sonic INFO swss#supervisord 2021-01-22 02:34:08,049 INFO stopped: nbrmgrd (terminated by SIGTERM)
Jan 22 02:34:08.100638 sonic INFO swss#supervisord 2021-01-22 02:34:08,050 INFO stopped: vrfmgrd (terminated by SIGTERM)
Jan 22 02:34:09.520725 sonic INFO bgp#supervisord 2021-01-22 02:34:07,043 INFO exited: bgpcfgd (exit status 255; not expected)
Jan 22 02:34:09.520725 sonic INFO bgp#supervisord 2021-01-22 02:34:08,050 WARN received SIGTERM indicating exit request
Jan 22 02:34:09.520725 sonic INFO bgp#supervisord 2021-01-22 02:34:08,050 INFO waiting for fpmsyncd, zebra, bgpd, supervisor-proc-exit-listener, staticd, rsyslogd to die
Jan 22 02:34:09.520725 sonic INFO bgp#supervisord 2021-01-22 02:34:09,052 INFO stopped: fpmsyncd (terminated by SIGTERM)
Jan 22 02:34:10.057636 sonic NOTICE bgp#staticd[51]: Terminating on signal
Jan 22 02:34:11.263372 sonic INFO containerd[530]: time="2021-01-22T02:34:11.263161584Z" level=info msg="shim reaped" id=cfeffc60df70302088acfb5963eab5ce6533af81a4e38376a248a8de653c12c2
Jan 22 02:34:11.273417 sonic INFO dockerd[549]: time="2021-01-22T02:34:11.273254596Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jan 22 02:34:11.370482 sonic INFO bgp.sh[1639]: 0
Jan 22 02:34:11.425760 sonic INFO bgp.sh[13607]: bgp`
```

Dockers started to crash/exit one by one but eventually the converged to state when only bgp docker was down:
```
admin@sonic:~$ docker ps -a
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                     PORTS               NAMES
187951f8bfe9        docker-sonic-telemetry:latest        "/usr/bin/supervisord"   5 weeks ago         Up 10 minutes                                  telemetry
0f55469028d2        docker-sonic-mgmt-framework:latest   "/usr/bin/supervisord"   5 weeks ago         Up 10 minutes                                  mgmt-framework
a7caf83c530d        docker-snmp-sv2:latest               "/usr/bin/supervisord"   5 weeks ago         Up 10 minutes                                  snmp
fb7e0583fd53        docker-router-advertiser:latest      "/usr/bin/docker-ini…"   5 weeks ago         Up 11 minutes                                  radv
156ff19ca002        docker-dhcp-relay:latest             "/usr/bin/docker_ini…"   5 weeks ago         Up 11 minutes                                  dhcp_relay
f551878b30cd        docker-lldp-sv2:latest               "/usr/bin/docker-lld…"   5 weeks ago         Up 13 minutes                                  lldp
57f513ac1e51        docker-syncd-bfn:latest              "/usr/bin/supervisord"   5 weeks ago         Up 11 minutes                                  syncd
0e11acb14e48        docker-teamd:latest                  "/usr/bin/supervisord"   5 weeks ago         Up 11 minutes                                  teamd
95f14880038e        docker-orchagent:latest              "/usr/bin/docker-ini…"   5 weeks ago         Up 11 minutes                                  swss
cfeffc60df70        docker-fpm-frr:latest                "/usr/bin/supervisord"   5 weeks ago         Exited (0) 9 minutes ago                       bgp
e352e54eebd7        docker-platform-monitor:latest       "/usr/bin/docker_ini…"   5 weeks ago         Up 13 minutes                                  pmon
31a3a86623f5        docker-database:latest               "/usr/local/bin/dock…"   5 weeks ago         Up 13 minutes                                  database
admin@sonic:~$

```
 
SONiC and platform info:

```
admin@sonic:~$ show version

SONiC Software Version: SONiC.201911.124-dirty-20200916.052834
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64
Build commit: 75068f3a
Build date: Wed Sep 16 10:57:59 UTC 2020
Built by: johnar@jenkins-worker-11

Platform: x86_64-accton_wedge100bf_65x-r0
HwSKU: mavericks
ASIC: barefoot
Serial Number: AJ24010220
Uptime: 02:56:09 up 16 min,  2 users,  load average: 1.13, 1.13, 0.83

Docker images:
REPOSITORY                    TAG                                IMAGE ID            SIZE
docker-syncd-bfn              201911.124-dirty-20200916.052834   32b9fe2f932f        2.42GB
docker-syncd-bfn              latest                             32b9fe2f932f        2.42GB
docker-sonic-telemetry        201911.124-dirty-20200916.052834   617826bc9a8f        353MB
docker-sonic-telemetry        latest                             617826bc9a8f        353MB
docker-router-advertiser      201911.124-dirty-20200916.052834   9b699a670fca        289MB
docker-router-advertiser      latest                             9b699a670fca        289MB
docker-platform-monitor       201911.124-dirty-20200916.052834   fd936bef89f4        358MB
docker-platform-monitor       latest                             fd936bef89f4        358MB
docker-fpm-frr                201911.124-dirty-20200916.052834   d6b885f733da        334MB
docker-fpm-frr                latest                             d6b885f733da        334MB
docker-lldp-sv2               201911.124-dirty-20200916.052834   216401e5de06        311MB
docker-lldp-sv2               latest                             216401e5de06        311MB
docker-dhcp-relay             201911.124-dirty-20200916.052834   8169f54ace47        299MB
docker-dhcp-relay             latest                             8169f54ace47        299MB
docker-database               201911.124-dirty-20200916.052834   7488764bd033        289MB
docker-database               latest                             7488764bd033        289MB
docker-sflow                  201911.124-dirty-20200916.052834   bd4b68c7aed9        315MB
docker-sflow                  latest                             bd4b68c7aed9        315MB
docker-teamd                  201911.124-dirty-20200916.052834   8c7e728dd76e        314MB
docker-teamd                  latest                             8c7e728dd76e        314MB
docker-snmp-sv2               201911.124-dirty-20200916.052834   0e934bb4a16e        348MB
docker-snmp-sv2               latest                             0e934bb4a16e        348MB
docker-orchagent              201911.124-dirty-20200916.052834   606edbf232b5        333MB
docker-orchagent              latest                             606edbf232b5        333MB
docker-nat                    201911.124-dirty-20200916.052834   ee58c0eeee6d        316MB
docker-nat                    latest                             ee58c0eeee6d        316MB
docker-sonic-mgmt-framework   201911.124-dirty-20200916.052834   fb03fe2259e0        430MB
docker-sonic-mgmt-framework   latest                             fb03fe2259e0        430MB
```

**Comment by lulu-tsai** [comment]
Hi,
I'm facing the same issue here.
Have you solve this problem?

Thanks,
Lulu

**Comment by gcupryn** [comment]
Hi @lulu-tsai ,
please note that error is caused by fact that I have used -1 in IP address:
 "Vlan100|192.168.-1.1/24": {}
So to fix the issue I've just used proper IP address in my JSON file.
