### ISSUE TITLE
 Error in config_db causes multiple containers to shutdown after a config reload

### ISSUE THREAD

**Issue by otikare1990** [Azure/SONiC#770]
============================================================================================
**A syntactical error in config_db causes config reload to fail with the following  reason :** 
============================================================================================

admin@sonic-ld468:~$ sudo config reload -y
Executing stop of service swss...
Executing stop of service lldp...
Executing stop of service pmon...
Executing stop of service bgp...
Running command: /usr/local/bin/sonic-cfggen -j /etc/sonic/init_cfg.json -j /etc/sonic/config_db.json --write-to-db
Traceback (most recent call last):
  File "/usr/local/bin/sonic-cfggen", line 432, in <module>
    main()
  File "/usr/local/bin/sonic-cfggen", line 328, in main
    _process_json(args, data)
  File "/usr/local/bin/sonic-cfggen", line 237, in _process_json
    deep_update(data, FormatConverter.to_deserialized(json.load(stream)))
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
>>>>>>>>>
**json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 153 column 9 (char 4730)**

============================================================================================
**Because of this, multiple containers are shutdown and the CLI also remains stuck. The only way to recover is to correct the error in config_db.json and then REBOOT the device instead of reload**
============================================================================================

Before CONFIG reload :

 docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS               NAMES
1a7f9e848c92        docker-snmp:latest                "/usr/local/bin/supe…"   2 minutes ago       Up 2 minutes                            snmp
e9a0cbe8b1bc        docker-router-advertiser:latest   "/usr/bin/docker-ini…"   5 minutes ago       Up 5 minutes                            radv
4d62d4fd0a05        docker-dhcp-relay:latest          "/usr/bin/docker_ini…"   5 minutes ago       Up 5 minutes                            dhcp_relay
17d767d9a2fd        docker-lldp:latest                "/usr/bin/docker-lld…"   5 minutes ago       Up 5 minutes                            lldp
56843f951a76        docker-syncd-brcm:latest          "/usr/local/bin/supe…"   5 minutes ago       Up 5 minutes                            syncd
dcd8b6070342        docker-teamd:latest               "/usr/local/bin/supe…"   5 minutes ago       Up 5 minutes                            teamd
171d23b636c5        docker-orchagent:latest           "/usr/bin/docker-ini…"   5 minutes ago       Up 5 minutes                            swss
8adde3318038        docker-fpm-frr:latest             "/usr/bin/docker_ini…"   5 minutes ago       Up 5 minutes                            bgp
a3e1d10eb142        docker-platform-monitor:latest    "/usr/bin/docker_ini…"   5 minutes ago       Up 5 minutes                            pmon
fba67d67b19b        docker-database:latest            "/usr/local/bin/dock…"   2 weeks ago         Up 6 minutes                            database

============================================================================================\
AFTER CONFIG RELOAD :
============================================================================================

admin@sonic-ld468:~$ docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS               NAMES
dcd8b6070342        docker-teamd:latest      "/usr/local/bin/supe…"   8 minutes ago       Up 8 minutes                            teamd
fba67d67b19b        docker-database:latest   "/usr/local/bin/dock…"   2 weeks ago         Up 9 minutes                            database

**build commit is 755c7379**

**Comment by otikare1990** [comment]
At times even REBOOT fails and a  containers including syncd, teamd ,swss fail to run.

pr  7 22:24:25.402293 sonic ERR monit[546]: 'teamd|teamsyncd' status failed (1) -- '/usr/bin/teamsyncd' is not running in host
Apr  7 22:24:25.402826 sonic ERR monit[546]: 'teamd|teammgrd' status failed (1) -- '/usr/bin/teammgrd' is not running in host
Apr  7 22:24:25.403421 sonic ERR monit[546]: 'syncd|syncd' status failed (1) -- '/usr/bin/syncd' is not running in host
Apr  7 22:24:25.418968 sonic ERR monit[546]: 'syncd|dsserve' status failed (1) -- '/usr/bin/dsserve /usr/bin/syncd' is not running in host
Apr  7 22:24:25.427185 sonic ERR monit[546]: 'swss|orchagent' status failed (1) -- '/usr/bin/orchagent -d /var/log/swss' is not running in host
Apr  7 22:24:25.435192 sonic ERR monit[546]: 'swss|portsyncd' status failed (1) -- '/usr/bin/portsyncd' is not running in host
Apr  7 22:24:25.467160 sonic ERR monit[546]: 'swss|neighsyncd' status failed (1) -- '/usr/bin/neighsyncd' is not running in host
Apr  7 22:24:25.475184 sonic ERR monit[546]: 'swss|fdbsyncd' status failed (1) -- '/usr/bin/fdbsyncd' is not running in host
Apr  7 22:24:25.487212 sonic ERR monit[546]: 'swss|vrfmgrd' status failed (1) -- '/usr/bin/vrfmgrd' is not running in host
Apr  7 22:24:25.507209 sonic-ld468 ERR monit[546]: 'swss|vlanmgrd' status failed (1) -- '/usr/bin/vlanmgrd' is not running in host
Apr  7 22:24:25.519246 sonic-ld468 ERR monit[546]: 'swss|intfmgrd' status failed (1) -- '/usr/bin/intfmgrd' is not running in host
Apr  7 22:24:25.547161 sonic-ld468 ERR monit[546]: 'swss|portmgrd' status failed (1) -- '/usr/bin/portmgrd' is not running in host
Apr  7 22:24:25.558451 sonic-ld468 ERR monit[546]: 'swss|buffermgrd' status failed (1) -- '/usr/bin/buffermgrd -l' is not running in host
Apr  7 22:24:25.571196 sonic-ld468 ERR monit[546]: 'swss|nbrmgrd' status failed (1) -- '/usr/bin/nbrmgrd' is not running in host
Apr  7 22:24:25.599007 sonic-ld468 ERR monit[546]: 'swss|vxlanmgrd' status failed (1) -- '/usr/bin/vxlanmgrd' is not running in host
Apr  7 22:24:25.611217 sonic-ld468 ERR monit[546]: 'swss|coppmgrd' status failed (1) -- '/usr/bin/coppmgrd' is not running in host
Apr  7 22:24:25.627010 sonic-ld468 ERR monit[546]: 'swss|tunnelmgrd' status failed (1) -- '/usr/bin/tunnelmgrd' is not running in host
Apr  7 22:24:25.887239 sonic-ld468 INFO dhclient[1368]: DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 13
Apr  7 22:24:25.887468 sonic-ld468 INFO dhclient[1368]: DHCPOFFER of 172.24.81.254 from 172.24.81.159
Apr  7 22:24:25.887588 sonic-ld468 INFO dhclient[1368]: DHCPREQUEST for 172.24.81.254 on eth0 to 255.255.255.255 port 67
Apr  7 22:24:25.887703 sonic-ld468 INFO dhclient[1368]: DHCPNAK from 172.24.81.159




admin@sonic-ld468:~$ docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS               NAMES
6d02f65574e0        docker-snmp:latest                "/usr/local/bin/supe…"   10 minutes ago      Up 10 minutes                           snmp
1825a4ebbd88        docker-router-advertiser:latest   "/usr/bin/docker-ini…"   12 minutes ago      Up 12 minutes                           radv
00f6ea308771        docker-dhcp-relay:latest          "/usr/bin/docker_ini…"   13 minutes ago      Up 13 minutes                           dhcp_relay
931ebb5d2f82        docker-lldp:latest                "/usr/bin/docker-lld…"   13 minutes ago      Up 13 minutes                           lldp
e4fac11d7070        docker-fpm-frr:latest             "/usr/bin/docker_ini…"   14 minutes ago      Up 13 minutes                           bgp
fba67d67b19b        docker-database:latest            "/usr/local/bin/dock…"   2 weeks ago         Up 14 minutes                           database

admin@sonic:~$ ls -l /var/core
total 0
